version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./src:/app/src
    environment:
      - DB_URL=postgres://caracterizacion:caracterizacion903452@db:5432/caracterizacion
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: caracterizacion
      POSTGRES_PASSWORD: caracterizacion903452
      POSTGRES_DB: caracterizacion
    volumes:
      - ./db_data:/var/lib/postgresql/data
# volumes:
#   db_data:
# postgresql://postgres:kYROy3LPqjk1fOBnzKt9@containers-us-west-150.railway.app:7224/railway
